camunda.bpm:
  admin-user:
    id: demo
    password: demo
    firstName: Demo
  filter:
    create: All tasks
  authorization:
    enabled: off

spring:
  application:
    name: orchestrator

server:
  port: 8084
  
eureka:
  server:
    host: ${spring.application.name}:8761
  client:
    serviceUrl:
      defaultZone: http://${eureka.server.host}/eureka
    fetch-registry: false
    register-with-eureka: true
