server.port: 8585

spring:
  application.name: uCard

eureka:
  server:
    host: localhost:8761
  client:
    serviceUrl:
      defaultZone: http://${eureka.server.host}/eureka
    register-with-eureka: true
    fetch-registry: false

